// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('biligual test', function () {
  this.timeout(120000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('biligual test', async function () {
    await driver.get("https://ship-this.herokuapp.com/")
    await driver.manage().window().setRect(1366, 768)
    await driver.findElement(By.css(".v-select__selections")).click()
    await driver.findElement(By.css("#list-item-77-1 .v-list-item__title")).click()
    assert(await driver.findElement(By.linkText("Inicio")).getText() == "Inicio")
  })
})
