// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('changeCost', function () {

  this.timeout(120000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  // afterEach(async function () {
  //   await driver.quit();
  // })
  it('changeCost', async function () {
    await driver.get("https://ship-this-backoffice.herokuapp.com/")
    await driver.findElement(By.id("input-37")).click()
    await driver.findElement(By.id("input-37")).sendKeys("admin@gmail.com")
    await driver.findElement(By.id("input-41")).click()

    await driver.findElement(By.id("input-41")).sendKeys("password")
    await driver.findElement(By.css(".v-btn__content")).click()

    setTimeout(() => {
      async function funcy() {
        await driver.findElement(By.css(".dashboard-item:nth-child(5) > .pa-4")).click()
      }
      funcy();
    }, 5000);
    setTimeout(() => {
      async function funcy() {
        await driver.findElement(By.css("div:nth-child(1) > .row > .col-sm-6 .v-expansion-panel-header__icon > .v-icon")).click()
      }
      funcy();
    }, 10000);
    setTimeout(() => {
      async function funcy() {
        await driver.findElement(By.id("input-142")).click()
      }
      funcy();
    }, 20000);
    setTimeout(() => {
      async function funcy() {
        await driver.findElement(By.id("input-142")).sendKeys(Key.chord(Key.CONTROL, "a"), "8.00");
      }
      funcy();
    }, 20000);
    setTimeout(() => {
      async function funcy() {
        await driver.findElement(By.css(".success > .v-btn__content")).click()
      }
      funcy();
    }, 20000);
    setTimeout(() => {
      async function funcy() {
        assert(await driver.findElement(By.css(".v-snack__content")).getText() == "The actualization have been successfully")
      }
      funcy();
    }, 25000);
  })
})
